config/routes.rb
Rails.application.routes.draw do
  resources :tasks
  root to: "home#index"
  devise_for :users
  resources :users, except: [:index,:create,:new,] do
    resources :categories
  end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  belongs_to :user
end

app/models/task.rb
class Task < ApplicationRecord
  belongs_to :user_id
  belongs_to :category
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :categories
  has_many :tasks, through: :categories
  validates :first_name, :last_name, presence: true
  validates_confirmation_of :password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    protect_from_forgery with: :exception

    before_action :update_allowed_parameters, if: :devise_controller?
  
    protected
    def set_category
      @category = current_user.categories.find(params[:category_id] || params[:id])
    end
  
    def update_allowed_parameters
      devise_parameter_sanitizer.permit(:sign_up) { |u| u.permit(:first_name, :last_name, :email, :password)}
      devise_parameter_sanitizer.permit(:account_update) { |u| u.permit(:first_name, :last_name, :email, :password, :current_password)}
    end
    
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_category, only: [ :show, :update, :destroy]
  
  def index
    @categories = current_user.categories
  end

  def create
    @category = current_user.categories.build(category_params)
    if @category.save
      redirect_to categories_path
    else
      render :new
    end
  end

  def update
    if @category.update(category_params)
      redirect_to category_tasks_path(category_id: @category.id)
    else
      render :show
    end
  end

  def destroy
    @category.destroy
    redirect_to categories_url
  end

  private

    def category_params
      params.require(:category).permit(:name, :description)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :authenticate_user!
  before_action :set_category, only: [:show, :index, :create, :update, :destroy, :set_task] 
  before_action :set_task, only: [:create, :update, :destroy, :show]

  def index
    @tasks = @category.tasks
  end

  def due 
    @due_tasks = current_user.tasks.where(is_done: false, due_date: Date.today)
  end

  def create
    @task = @category.tasks.build(task_params)
    @task.save
    redirect_to category_tasks_path(category_id: @category.id)
  end

  def update
    if @task.update(task_params)
      redirect_to category_tasks_path(category_id: @category.id)
    else
      render :show
    end
  end

  def destroy
    @task.destroy
    redirect_to category_tasks_path(category_id: @task.category_id)
  end

  private
    def set_task
      @task = @category.tasks.find(params[:id])
    end

    def task_params
      params.require(:task).permit(:name, :description, :due_date, :is_done, :category_id)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!, only: [ :show, :edit, :update, :destroy]
  
  def update
    if current_user.update(user_params)
      redirect_to user_path
    else
      render :edit
    end
  end

  def destroy
    current_user.destroy
    redirect_to users_url, notice: 'User was successfully destroyed.'
  end

  private
    def user_params
      params.require(:user).permit(:email, :first_name, :last_name)
    end
    
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/categories/edit.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">Editing category</h1>

  <%= render "form", category: @category %>

  <%= link_to "Show this category", @category, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  <%= link_to "Back to categories", categories_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/categories/index.html.erb
<div class="w-full">
  <% if notice.present? %>
    <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
  <% end %>

  <div class="flex justify-between items-center">
    <h1 class="font-bold text-4xl">Categories</h1>
    <%= link_to 'New category', new_category_path, class: "rounded-lg py-3 px-5 bg-blue-600 text-white block font-medium" %>
  </div>

  <div id="categories" class="min-w-full">
    <%= render @categories %>
  </div>
</div>

app/views/categories/new.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">New category</h1>

  <%= render "form", category: @category %>

  <%= link_to 'Back to categories', categories_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/categories/show.html.erb
<%= render partial: "shared/header", locals: {title: "Category Details"} %>
<div class="flex flex-col grow p-4">
  <%= form_with scope: :category, method: 'put', url: "/users/#{current_user.id}/categories/#{@category.id}" do |f| %>
    
        <div class="field">
          <%= f.label "Title" , class: "font-semibold text-lg"%><br />
          <%= f.text_field :name, value: @category.name, class: "bg-slate-50 border-0 w-full p-0" %>
        </div>

        <div class="field">
          <%= f.label :description , class: "font-semibold text-lg"%><br />
          <%= f.text_area :description, value: @category.description, class: "bg-slate-50 border-0 w-full p-0" %>
        </div>

      <div class="text-center">
        <%= f.submit "Save Changes", class: "bg-sky-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded-full w-8/12 m-auto mt-2" %>
      </div>

      <%= link_to "Discard Changes", user_category_tasks_path(user_id: current_user.id, category_id: @category.id), class: "bg-sky-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded-full w-8/12 m-auto block text-center mt-2" %>
  <% end %>
</div>
<%= render partial: "shared/footer", locals: {tab: "tasks"} %>

app/views/home/index.html.erb
<%if current_user%>

    <%controller.redirect_to user_categories_path(user_id: current_user.id)%>

<% else %>
    
    <div class="h-screen flex flex-col justify-around">
        <div class="app-title text-center text-3xl font-bold text-sky-500">
            <span>Do.me</span>
        </div>
        <div class="action-container flex flex-col text-center">
            <a class="bg-sky-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded-full w-8/12 m-auto" href=<%=new_user_registration_path%>>
                Create an account
            </a>
            <span>Already have an account?</span>
            <span>Tap here to <a class="underline" href=<%=new_user_session_path%>>sign in</a>!</span>
        </div>
    </div>

<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Taskmanager</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <main class="container mx-auto mt-28 px-5 flex">
      <%= yield %>
    </main>
  </body>
</html>

app/views/shared/_footer.html.erb
<div class="flex justify-around text-center bg-white shadow-inner p-4">
    <a class="flex flex-col">
        <i class="fas fa-check-circle text-2xl"></i>
        <span class="font-semibold">Tasks</span>
    </a>
    <a class="flex flex-col">
        <i class="fas fa-cog text-2xl"></i>
        <span class="font-semibold">Settings</span>
    </a>
</div>

app/views/shared/_header.html.erb
<div class="text-xl font-semibold text-center shadow-md bg-white p-4"> <%=title%> </div>

app/views/tasks/due.html.erb
<%= render partial: "shared/header", locals: {title: "Due Tasks"} %>


<div class="flex flex-col grow p-4">
  <% @due_tasks.each do |task|%>
    <div class="flex justify-between border-b border-gray-300 border-solid mb-1 pb-1 text-lg">
      <div>
        <a class="<%= task.is_done ? "line-through" : ""%>" href="<%= category_task_path(category_id: task.category_id, id: task.id) %>"><%= task.name %></a>
      </div>
      <div>
        <a class="fas fa-edit" href="<%= category_task_path(category_id: task.category_id, id: task.id) %>"></a>
        <a class="fas fa-trash" href="/categories/<%=task.category_id%>/tasks/<%=task.id%>" data-method="delete" data-confirm="Are you sure you want to delete this task?"></a>
      </div>
    </div>
  <%end%>
</div>

<%= render partial: "shared/footer", locals: {tab: "tasks"} %>

app/views/tasks/index.html.erb
<div class="text-xl font-semibold flex justify-between shadow-md bg-white p-4 px-6 sticky top-0">

  <%=@category.name%>
  <div>
    <a class="fas fa-info-circle" href="<%= edit_user_category_path(id: @category.id, user_id: current_user.id) %>"></a>
  </div>
</div>

<div class="flex flex-col grow p-4">
    <div class="categories-container flex flex-wrap justify-around">
    
    </div>
</div>

<%= render partial: "shared/footer", locals: {tab: "tasks"} %>

app/views/tasks/show.html.erb
<div class="mx-auto md:w-2/3 w-full flex">
  <div class="mx-auto">
    <% if notice.present? %>
      <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
    <% end %>

    <%= render @task %>

    <%= link_to 'Edit this task', edit_task_path(@task), class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <div class="inline-block ml-2">
      <%= button_to 'Destroy this task', task_path(@task), method: :delete, class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 font-medium" %>
    </div>
    <%= link_to 'Back to tasks', tasks_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  </div>
</div>

app/views/users/edit.html.erb
<%= render partial: "shared/header", locals: {title: "Profile"} %>
<div class="flex flex-col grow p-4 md:p-10">
  <%= form_with scope: :user, url: "/users/#{current_user.id}", method: 'put' do |f| %>
    
        <div class="field">
          <%= f.label :email , class: "font-semibold text-lg md:text-2xl"%><br />
          <%= f.email_field :email, value: current_user.email, class: "bg-slate-50 border-0 w-full p-0 md:text-xl"%>
        </div>

        <div class="field">
          <%= f.label :first_name , class: "font-semibold text-lg md:text-2xl"%><br />
          <%= f.text_field :first_name, value: current_user.first_name, class: "bg-slate-50 border-0 w-full p-0 md:text-xl" %>
        </div>

        <div class="field">
          <%= f.label :last_name , class: "font-semibold text-lg md:text-2xl"%><br />
          <%= f.text_field :last_name, value: current_user.last_name, class: "bg-slate-50 border-0 w-full p-0 md:text-xl" %>
        </div>
      <div class="text-center">
        <%= f.submit "Save Changes", class: "bg-sky-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded-full w-8/12 m-auto mt-2 md:text-xl" %>
      </div>
      <%= link_to "Discard Changes", user_path(user_id: current_user.id), class: "bg-sky-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded-full w-8/12 m-auto block text-center mt-2 md:text-xl" %>
  <% end %>
</div>
<%= render partial: "shared/footer", locals: {tab: "settings"} %>

app/views/users/index.html.erb
<div class="w-full">
  <% if notice.present? %>
    <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
  <% end %>

  <div class="flex justify-between items-center">
    <h1 class="font-bold text-4xl">Users</h1>
    <%= link_to 'New user', new_user_path, class: "rounded-lg py-3 px-5 bg-blue-600 text-white block font-medium" %>
  </div>

  <div id="users" class="min-w-full">
    <%= render @users %>
  </div>
</div>

app/views/users/show.html.erb
<div class="mx-auto md:w-2/3 w-full flex">
  <div class="mx-auto">
    <% if notice.present? %>
      <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
    <% end %>

    <%= render @user %>

    <%= link_to 'Edit this user', edit_user_path(@user), class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <div class="inline-block ml-2">
      <%= button_to 'Destroy this user', user_path(@user), method: :delete, class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 font-medium" %>
    </div>
    <%= link_to 'Back to users', users_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  </div>
</div>